<h1>Machine learning algorithms.<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Linear-regression" data-toc-modified-id="Linear-regression-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Linear regression</a></span><ul class="toc-item"><li><span><a href="#Hypothesis" data-toc-modified-id="Hypothesis-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Hypothesis</a></span></li><li><span><a href="#Cost-function---Mean-squared-error" data-toc-modified-id="Cost-function---Mean-squared-error-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Cost function - Mean squared error</a></span></li><li><span><a href="#Gradient-descent" data-toc-modified-id="Gradient-descent-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Gradient descent</a></span></li><li><span><a href="#Feature-scaling-and-mean-normalization" data-toc-modified-id="Feature-scaling-and-mean-normalization-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Feature scaling and mean normalization</a></span></li><li><span><a href="#Normal-equasion" data-toc-modified-id="Normal-equasion-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Normal equasion</a></span></li></ul></li><li><span><a href="#Linear-regression-examples" data-toc-modified-id="Linear-regression-examples-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Linear regression examples</a></span><ul class="toc-item"><li><span><a href="#Plot-hypothesis" data-toc-modified-id="Plot-hypothesis-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Plot hypothesis</a></span></li></ul></li></ul></div>

# Linear regression

n - number of features <br>
m - number of training examples <br>
$x^{(i)}$ - $i^{th}$ input variable <br>
$y^{(i)}$ - $i^{th}$ output variable

## Hypothesis

Parameters: <br>
&emsp; $\theta_0, \theta_1,...\theta_n = \theta$ <br><br>
Hypothesis: <br>
&emsp; $h_\theta(x) = \theta_0x_0+\theta_1x_1+...+\theta_nx_n = \theta^Tx$

## Cost function - Mean squared error

Cost function: <br>
&emsp; $J(\theta) = \frac{1}{2m} \sum \limits _{i=1} ^m (h_\theta(x^{(i)})-y^{(i)})^2$ <br><br>
Vectorized cost function: <br>
&emsp; $J(\theta) = \frac{1}{2m}(X\theta - y)^T(X\theta - y)$

## Gradient descent

Gradient descent algorithm: <br>
&emsp; $\theta_j := \theta_j - \alpha \frac{\partial}{\partial\theta_j}J(\theta)$ <br>
&emsp;$\theta_j := \theta_j - \alpha \frac{1}{m} \sum \limits _{i=1} ^m (h_\theta(x^{(i)})-y^{(i)})x_j^{(i)}$ &emsp; for j=0...n,  $x_0=1$ <br><br>
Vectorized gradient descent: <br>
&emsp; $\theta = \theta - \alpha \frac{1}{m} ((X\theta - y)^T X)^T = \theta - \alpha \frac{1}{m} X^T (X\theta - y)$

## Feature scaling and mean normalization

$\mu_i - mean$ <br>
$\sigma_i$ - standard deviation <br><br>
Feature scaling and mean normalization: <br>
&emsp; $x_i = \frac{x_i - \mu_i}{\sigma_i}$ <br><br>
Vectorized feature scaling and mean normalization: <br>
&emsp; $\mu \in \mathbb{R^n}$ <br>
&emsp; $\sigma \in \mathbb{R^n}$ <br>
&emsp; $t \in \mathbb{1}^m$ <br><br>
&emsp; $X_{normalize} = (X - t\mu^T) \oslash (t\sigma^T)$

## Normal equasion

min of $J(\theta) = \frac{\partial}{\partial\theta}J(\theta) = \frac{\partial}{\partial\theta} \frac{1}{2m} \sum \limits _{i=1} ^m (h_\theta(x^{(i)})-y^{(i)})^2 = 0 => \theta = (X^TX)^{-1}X^Ty$ <br>

# Linear regression examples

## Plot hypothesis

In [10]:
import numpy as np
dataset = np.loadtxt('datasets/food_truck.csv', delimiter=',')

In [14]:
dataset[:, 1]
https://www.youtube.com/watch?v=QUT1VHiLmmI

In [4]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [16]:
b = np.array([[1,2,3],[4,5,6]], dtype='int16')
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
b.dtype

dtype('int16')

In [20]:
b.itemsize

2

In [21]:
b.nbytes

12

In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
a[1,1]

5

In [34]:
a[0,:]

array([1, 2, 3])

In [35]:
a[:, 0]

array([1, 4, 7])

In [38]:
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)